version: '3'

services:
  service-a:
    build: ./service-a
    ports:
      - "8080:8080"
    depends_on:
      - service-b
      - zipkin

  service-b:
    build: ./service-b
    ports:
      - "8081:8081"
    depends_on:
      - zipkin

  zipkin:
    image: openzipkin/zipkin
    ports:
      - "9411:9411"
