version: "3.8"
services:
  serviço_a:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - zipkin-network

  serviço_b:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    networks:
      - zipkin-network

networks:
  zipkin-network:
    driver: bridge
