receivers:
  otlp:
    protocols:
      grpc:

exporters:

  zipkin:
    endpoint: "http://observability:9411/api/v2/spans"
    format: proto
  debug:

processors:
  batch:


service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [zipkin]